language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-5 liballegro5-dev xvfb
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
  - bash scripts/test.bash