language: cpp
compiler: gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-5 liballegro5-dev xvfb fakeroot gtk2.0
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - export DISPLAY=:99.0;
  - sh -e /etc/init.d/xvfb start;

script:
  - bash scripts/test.bash