install:
  - git submodule update --init --recursive
  - ps: Install-Package Allegro -Force
  - dir %USERPROFILE%\.nuget\packages

build: off

test_script:
  - set path=%path%;C:\mingw\bin
  - bash scripts/test.bash